name: heart-disease
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.7.7
  - pip:
      - numpy==1.18.5
      - pandas==1.0.4
      - ipykernel==5.1.4
      - jupyter==1.0.0
      - sklearn==0.0
      - seaborn==0.10.0
      - pandas-profiling==2.8.0
