name: heart_disease_differential_privacy
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.7.7
  - pip:
      - numpy==1.18.5
      - pandas==1.0.4
      - ipykernel==5.1.4
      - jupyter==1.0.0
      - opendp-whitenoise==0.1.1.1
      - opendp-whitenoise-core==0.1.3
      - matplotlib==3.1.3
